apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:fpm
      #   env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     value: "projetDevOps"
      #   ports:
      #   - containerPort: 80
      #   volumeMounts:
      #   - mountPath: /data
      #     name: data
      # volumes:
      # - name: data
---
kind: Service
apiVersion: v1
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - name: php
      protocol: TCP
      port: 80
      targetPort: 80
