apiVersion: v1
kind: Service
metadata:
  labels:
    name: php
  name: php
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: php
  type: LoadBalancer

apiVersion: v1
kind: Pod
metadata:
  name: php
  labels:
    name: php
spec:
  containers:
    - name: php
      image: php
      env:
        - name: PMA_HOST
          value: mysql-service
      ports: 
        - containerPort: 80
          name: php
